---
- name: Instalar herramientas en Mac con Homebrew y configurar Oh My Zsh
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Actualizar Homebrew
      become: false
      command: brew update
      changed_when: false

    - name: Instalar Git
      become: false
      command: brew install git
      args:
        creates: /usr/local/bin/git

    - name: Git branch por defecto main
      become: false
      command: git config --global init.defaultBranch main

    - name: Git Configurar correo y usuario globalmente
      become: false
      shell: >
        git config --global user.email "cacevedod@devco.com.co" && git config --global user.name "cacevedod"

    - name: Generar claves SSH
      become: false
      command: ssh-keygen -t rsa -b 4096 -C "cacevedod@devco.com.co" -f ~/.ssh/id_rsa -N ''

    - name: Mostrar clave pública SSH
      become: false
      command: cat ~/.ssh/id_rsa.pub
      register: public_key

    - name: Imprimir clave pública SSH
      debug:
        var: public_key.stdout

    - name: Instalar NVM
      become: false
      command: brew install nvm
      args:
        creates: /usr/local/bin/nvm

    - name: Configurar NVM en el archivo de perfil (zsh)
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: 'export NVM_DIR="$HOME/.nvm"'
        state: present

    - name: Cargar NVM en el archivo de perfil (zsh)
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
        state: present

    - name: Instalar jEnv
      become: false
      command: brew install jenv

    - name: Configurar jEnv en el archivo de perfil (zsh)
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: 'eval "$(jenv init -)"'
        state: present

    - name: Instalar Java (OpenJDK)
      become: false
      command: brew install openjdk@11

    - name: symlink Java (OpenJDK)
      become: true
      command: ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

    - name: Configurar OpenJDK en el archivo de perfil (zsh)
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: 'export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"'
        state: present

    - name: configurar para compiladores
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: 'export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"'
        state: present

    - name: Configurar Java con jEnv
      become: false
      command: jenv add /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home

    - name: Establecer versión de Java por defecto
      become: false
      command: jenv global 11.0

    #- name: Instalar Oh My Zsh
    #  become: false
    #  shell: >
    #    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    #- name: Establecer tema de Oh My Zsh
    #  become: false
    #  lineinfile:
    #    dest: ~/.zshrc
    #    line: 'ZSH_THEME="jaischeema"'
    #    state: present

    - name: Configurar plugins en el archivo de perfil de Oh My Zsh (zsh)
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: 'plugins=(git docker ansible terraform docker-compose brew)'
        state: present

    - name: Cargar configuración zsh
      become: false
      shell: source ~/.zshrc
